# Generated by Django 3.2.5 on 2021-08-07 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210721_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timeCreation',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
