# Generated by Django 3.2.5 on 2021-08-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210807_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreation',
            field=models.TimeField(auto_now=True),
        ),
    ]
