# Generated by Django 3.2.5 on 2021-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210807_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeCreation',
            field=models.TimeField(),
        ),
    ]
