# Generated by Django 3.2.5 on 2021-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210807_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timeCreation',
        ),
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
